engines:
  shellcheck:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - "app/**/*"
  - "bin/**/*"
  - "lib/**/*"
  - "**.rb"
  - "**.js"
exclude_paths:
- "spec/**/*"
- "vendor/**/*"
- ".codeclimate.yml"
