detectors:
  TooManyStatements:
    exclude:
      - Versionaire#Version
  UncommunicativeMethodName:
    exclude:
    - Kernel#Version
    - Versionaire#Version
  UtilityFunction:
    exclude:
    - Kernel#Version
