inherit_gem:
  caliber: config/all.yml

Layout/SpaceBeforeBrackets:
  Exclude:
    - "spec/lib/versionaire/cast_spec.rb"
Performance/Sum:
  Exclude:
    - "lib/versionaire/version.rb"
Style/IpAddresses:
  Exclude:
    - "spec/lib/versionaire/versionaire_spec.rb"
