inherit_from:
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/ruby.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/rake.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/performance.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/rspec.yml

Layout/SpaceBeforeBrackets:
  Exclude:
    - "spec/lib/versionaire/cast_spec.rb"
Performance/Sum:
  Exclude:
    - "lib/versionaire/version.rb"
Style/IpAddresses:
  Exclude:
    - "spec/lib/versionaire/version_spec.rb"
