inherit_from:
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/master/configurations/rubocop/ruby.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/master/configurations/rubocop/rspec.yml

Naming/MethodName:
  Exclude:
    - "lib/versionaire/conversion.rb"
