language: ruby
rvm:
- 2.3.0
script: bundle exec rake
notifications:
  email: false
  slack:
    secure: KIu3q08gnMHl9o4Klz2AzqnrfDpSjCBTDFXeqISxOY9le618He2JPR7oH5ZF4J/6rNBbMNUr6VoQx/sanCAwOcnVXQJPVW+ti1fzbWkZUHAPRxccFRHX+0R4IiC8kxwZwn4jspwPI/rz2F7FqlmnVf6lePTmMrrhkubkoia1v3NREk257PAu6KWUjWrkkjxnB1HvLo29h6bG+nCxU1YUe2Qc/LyVZJqp0z5JrOEElcnOhtlz6sc9erfOliPiRDaqvqHmky1S2RoXXDtCQi4W9Lklfme+kcJNK49dsBjhMeyrBTCR5UaKWfp0CObyF+yHjXP6x12FrXcowfyF2/MiwuXhBsD2Le/L6fbO2+oxZsJ31T1RSpzMnWa4xYfy+J0ffOghBo2nYskdL0NQlYGPozwyT5VT3/w20Xy6ABTEGkyO97hEZaYRt9Cuo3YNDsc1XVFe2INeWM+HOcQQTEFsukiu+H6kT8/V/npbAThRqyMbVUWAGoRbSxQr5Zla1RlYAzJjdQnsmTC4uzH3rXIHM5ZVNnL4rRz9GSftegZks4Uupri4JKliudgpu9F3LEQBxwcEz6w6M1mtUllLA9c2ORMnX9bHAgBPPnIG0q8TVdEzmmuEbeXby9KI0tojNXXrvI3JXOmjAFdt4q4jClGlRReuHM6akeoEv4Gi45HDVCc=
